const DEFAULT_CONTEXT = {
  topbarText: "Plateforme legaltech française • Process conforme • Réponse en 10 min",
  headerSubtitle: "Plateforme formalités d'entreprise",
  headerCtaHref: "/demande?service=creation",
  headerCtaLabel: "Démarrer ma formalité",
  headerCtaTrack: "header_primary",
  headerMobileCtaLabel: "Démarrer ma formalité",
};

const ROUTE_CONTEXT = {
  "/": {
    topbarText: "Plateforme legaltech française • Assistance rapide • Process conforme",
    headerSubtitle: "Plateforme formalités d'entreprise",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer ma demande",
    headerCtaTrack: "header_primary",
    headerMobileCtaLabel: "Démarrer ma demande",
  },
  "/creation-societe": {
    topbarText: "Création d'entreprise simplifiée • Réponse rapide • Accompagnement humain",
    headerSubtitle: "Création d'entreprise",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer ma création",
    headerCtaTrack: "creation_header_primary",
    headerMobileCtaLabel: "Démarrer ma création",
  },
  "/modification-societe": {
    topbarText: "Modification de société claire • Réponse rapide • Accompagnement humain",
    headerSubtitle: "Modification de société",
    headerCtaHref: "/demande?service=modification",
    headerCtaLabel: "Démarrer ma modification",
    headerCtaTrack: "modif_header_primary",
    headerMobileCtaLabel: "Démarrer ma modification",
  },
  "/fermeture-societe": {
    topbarText: "Fermeture de société simplifiée • Process rassurant • Support réactif",
    headerSubtitle: "Fermeture de société",
    headerCtaHref: "/demande?service=fermeture",
    headerCtaLabel: "Démarrer ma fermeture",
    headerCtaTrack: "fermeture_header_primary",
    headerMobileCtaLabel: "Démarrer ma fermeture",
  },
  "/guides": {
    topbarText: "Guides pratiques legaltech • Ressources actionnables • Mise à jour continue",
    headerSubtitle: "Guides et ressources",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer ma formalité",
    headerCtaTrack: "guides_header_primary",
    headerMobileCtaLabel: "Démarrer ma formalité",
  },
  "/guide-creation-sasu": {
    topbarText: "Guide création SASU • Mise à jour 2026 • Lecture 8 min",
    headerSubtitle: "Guide création SASU",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer ma création",
    headerCtaTrack: "guide_sasu_header",
    headerMobileCtaLabel: "Démarrer ma création",
  },
  "/guide-modification-siege-social": {
    topbarText: "Guide changement de siège • Mise à jour 2026 • Lecture 7 min",
    headerSubtitle: "Guide siège social",
    headerCtaHref: "/demande?service=modification",
    headerCtaLabel: "Démarrer ma modification",
    headerCtaTrack: "guide_siege_header",
    headerMobileCtaLabel: "Démarrer ma modification",
  },
  "/guide-fermeture-societe": {
    topbarText: "Guide fermeture • Mise à jour 2026 • Lecture 9 min",
    headerSubtitle: "Guide fermeture société",
    headerCtaHref: "/demande?service=fermeture",
    headerCtaLabel: "Démarrer ma fermeture",
    headerCtaTrack: "guide_fermeture_header",
    headerMobileCtaLabel: "Démarrer ma fermeture",
  },
  "/creation-societe-rapide": {
    topbarText: "Offre création express • Conversion rapide • Sans friction",
    headerSubtitle: "Offre création rapide",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer maintenant",
    headerCtaTrack: "ads_creation_header",
    headerMobileCtaLabel: "Démarrer maintenant",
  },
  "/modification-societe-urgente": {
    topbarText: "Offre modification urgente • Priorité 24h • Réponse rapide",
    headerSubtitle: "Offre modification urgente",
    headerCtaHref: "/demande?service=modification",
    headerCtaLabel: "Démarrer maintenant",
    headerCtaTrack: "ads_modif_header",
    headerMobileCtaLabel: "Démarrer maintenant",
  },
  "/fermeture-societe-rapide": {
    topbarText: "Offre fermeture rapide • Process clair • Réponse rapide",
    headerSubtitle: "Offre fermeture rapide",
    headerCtaHref: "/demande?service=fermeture",
    headerCtaLabel: "Démarrer maintenant",
    headerCtaTrack: "ads_fermeture_header",
    headerMobileCtaLabel: "Démarrer maintenant",
  },
  "/simulateur-couts": {
    topbarText: "Simulateur gratuit • Estimation en 30 secondes • Toutes formes juridiques",
    headerSubtitle: "Simulateur de coûts",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Parler à un expert",
    headerCtaTrack: "simulateur_header_primary",
    headerMobileCtaLabel: "Parler à un expert",
  },
  "/quiz-statut-juridique": {
    topbarText: "Quiz gratuit • Trouvez votre statut en 2 min • Résultat personnalisé",
    headerSubtitle: "Quiz statut juridique",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Parler à un expert",
    headerCtaTrack: "quiz_header_primary",
    headerMobileCtaLabel: "Parler à un expert",
  },
  "/documents-gratuits": {
    topbarText: "Modèles gratuits • Statuts conformes 2026 • Téléchargement immédiat",
    headerSubtitle: "Documents gratuits",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Parler à un expert",
    headerCtaTrack: "docs_header_primary",
    headerMobileCtaLabel: "Parler à un expert",
  },
  "/demande": {
    topbarText: "Tunnel de conversion • Formulaire rapide • Estimation immédiate",
    headerSubtitle: "Demande rapide",
    headerCtaHref: "/creation-societe",
    headerCtaLabel: "Voir nos services",
    headerCtaTrack: "demande_header_services",
    headerMobileCtaLabel: "Voir nos services",
  },
  "/mentions-legales": {
    topbarText: "Informations légales • Transparence • Conformité",
    headerSubtitle: "Mentions légales",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer ma formalité",
    headerCtaTrack: "legal_header_primary",
    headerMobileCtaLabel: "Démarrer ma formalité",
  },
  "/cgv": {
    topbarText: "Conditions de service • Transparence • Conformité",
    headerSubtitle: "Conditions générales",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer ma formalité",
    headerCtaTrack: "legal_header_primary",
    headerMobileCtaLabel: "Démarrer ma formalité",
  },
  "/confidentialite": {
    topbarText: "Protection des données • RGPD • Confiance",
    headerSubtitle: "Politique de confidentialité",
    headerCtaHref: "/demande?service=creation",
    headerCtaLabel: "Démarrer ma formalité",
    headerCtaTrack: "legal_header_primary",
    headerMobileCtaLabel: "Démarrer ma formalité",
  },
};

export function marketingShellContext(pathname = "/") {
  return {
    ...DEFAULT_CONTEXT,
    ...(ROUTE_CONTEXT[pathname] || {}),
  };
}
